# Generated by Django 2.1.2 on 2018-12-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Rating(stars)'),
        ),
    ]
