# Generated by Django 2.1.2 on 2018-12-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20181207_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
    ]
