# Generated by Django 2.1.2 on 2018-12-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='/home/alind/Downloads/FullSizeRender.jpg', upload_to='myrestaurants'),
        ),
    ]
