# Generated by Django 2.1.2 on 2018-12-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20181207_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.TextField(verbose_name='Dollars'),
        ),
    ]
