# Generated by Django 2.1.2 on 2018-12-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20181207_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50)),
                ('emp_name', models.CharField(max_length=50)),
                ('competency', models.CharField(max_length=50)),
                ('suggest', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='myapp.Restaurant'),
        ),
    ]
