# Generated by Django 2.1.2 on 2018-12-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20181210_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_img',
            field=models.ImageField(default='/home/', upload_to='Employee'),
            preserve_default=False,
        ),
    ]
