# Generated by Django 2.1.2 on 2018-12-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_employee_emp_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-emp_name']},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='emp_name',
        ),
    ]
